# Generated by Django 3.2.5 on 2021-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='affected_account_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='concept',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
