# Generated by Django 3.2.5 on 2021-07-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20210725_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comments',
            field=models.CharField(default='', max_length=250),
        ),
    ]
